version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-mcp-stack"
s3_prefix = "hello-mcp"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BearerToken=\"mcp-secret-token-12345\""
confirm_changeset = false
resolve_s3 = true
